name: 'Confirm Trello link included on Pull Request'
description: 'Confirm Trello link included on Pull Request'
inputs:
  link-regex: 
    description: 'URL to use reg ex search for'
    default: '(https:\/\/trello.com[^\)]*)'
outputs:
  msg:
    description: 'output of action'
runs:
  using: 'node12'
  main: 'index.js'