on: 
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [created, edited, opened, synchronize, reopened]
jobs:
  confirm-link:
    runs-on: ubuntu-latest
    name: Ensure Trello link present as attachment.
    steps:
    - name: Confirm Link
      id: confirm
      uses: delivered/trello-github-action/@master
      with:
        link-regex: '(https:\/\/trello.com[^\)]*)'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
