on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]
jobs:
  confirm-link:
    runs-on: ubuntu-latest
    name: Ensure Trello link present as attachment.
    steps:
    - name: Confirm Link
      id: confirm
      uses: delivered/trello-github-action/@MM-first-pr
      with:
        link-regex: '(https:\/\/trello.com[^\)]*)'
        repo-token: ${{ secrets.GITHUB_TOKEN }}